In [1]:
import pandas as pd
import numpy as np

In [4]:
s1 =pd.Series(np.random.randint(1,5,100))
s2 =pd.Series(np.random.randint(1,4,100))
s3 =pd.Series(np.random.randint(10000,30000,100))

print(s1,s2,s3)

0     4
1     4
2     3
3     3
4     1
     ..
95    2
96    3
97    4
98    1
99    3
Length: 100, dtype: int64 0     1
1     2
2     1
3     1
4     1
     ..
95    1
96    2
97    3
98    3
99    2
Length: 100, dtype: int64 0     27023
1     10107
2     15934
3     20820
4     28049
      ...
95    10734
96    26153
97    10393
98    24937
99    21624
Length: 100, dtype: int64

In [5]:
ho = pd.concat([s1,s2,s3],axis=1)
ho.head()

   0  1      2
0  4  1  27023
1  4  2  10107
2  3  1  15934
3  3  1  20820
4  1  1  28049

In [9]:
ho.rename(columns={0:'bedrooms',1:'bathrs',2:'price_sqr_meter'},inplace=True)
ho.head()

   bedrooms  bathrs  price_sqr_meter
0         4       1            27023
1         4       2            10107
2         3       1            15934
3         3       1            20820
4         1       1            28049

In [7]:
bigcolumn = pd.concat([s1, s2, s3], axis=0).to_frame(name='bigcolumn')
bigcolumn

    bigcolumn
0           4
1           4
2           3
3           3
4           1
..        ...
95      10734
96      26153
97      10393
98      24937
99      21624

[300 rows x 1 columns]

In [10]:
len(bigcolumn)

300

In [15]:
bigcolumn = bigcolumn.reset_index(drop=True)
bigcolumn

     level_0  index  bigcolumn
0          0      0          4
1          1      1          4
2          2      2          3
3          3      3          3
4          4      4          1
..       ...    ...        ...
295      295    295      10734
296      296    296      26153
297      297    297      10393
298      298    298      24937
299      299    299      21624

[300 rows x 3 columns]